open GenericCFG
open Utils

type modality =
  | May
  | Must
      (** Type for representing the approximation of the analysis. It can be
          either an over-approximation (May) or an under-approximation (Must) *)

type direction =
  | Forward
  | Backward
      (** Type for representing the direction of the analysis. It can be either
          forward or backward *)

type 'a local_state = { in_values : 'a; out_values : 'a }
(** Type for representing the local state of a node during a dataflow analysis.
    It contains the values of the analysis at the entry and exit of the node *)

type 'a global_state = 'a local_state NodeMap.t
(** Type for representing the global state of the analysis, which is a mapping
    from nodes to their local state *)

(** Module type specifying what a dataflow analysis must provide *)
module type S = sig
  type t
  (** Type for representing the elements of the analysis *)

  type cmd
  (** Type for representing the commands associated with each node *)

  type aux
  (** Type for representing auxiliary information that can be used in the gen
      and kill functions *)

  module Set : Set.S with type elt = t

  val modality : modality
  (** Modality of the analysis, either May or Must *)

  val direction : direction
  (** Direction of the analysis, either forward or backward *)

  val gen : (cmd, t) cfg * aux -> node -> Set.t
  (** Function for computing the gen set of a node. Takes a node and returns the
      set of elements generated by that node *)

  val kill : (cmd, t) cfg * aux -> node -> Set.t
  (** Function for computing the kill set of a node. Takes a node and returns
      the set of elements killed by that node *)

  val initial_node : (cmd, t) cfg -> node
  (** Initial node of the CFG, used for initializing the worklist algorithm *)

  val initial_node_state : (cmd, t) cfg -> Set.t
  (** Initial state for the initial node of the CFG *)

  val compute_initial_state : (cmd, t) cfg * aux -> Set.t
  (** Initial value for [in_values] and [out_values] for all nodes in the CFG.
      It should be the least element for a [May] analysis and the greatest
      element for a [Must] analysis *)

  val compute_aux_info : (cmd, t) cfg -> aux
  (** Function for getting auxiliary information from the CFG, which can be used
      in the gen and kill functions *)
end

(** Implementation of the worklist algorithm for a generic dataflow analysis.
    The functor takes a module of type [S] as input, which specifies the details
    of the analysis, and produces a module with a function [worklist_algorithm]
    that takes a CFG and returns the result of the analysis as a mapping from
    nodes to their local state *)
module Make (S : S) = struct
  include S

  let compute_edges cfg =
    let add_edge src dest =
      let src, dest =
        match direction with Forward -> (src, dest) | Backward -> (dest, src)
      in
      NodeMap.update src
        (Option.value ~default:[] >> List.cons dest >> Option.some)
    in
    NodeMap.fold
      (fun src edge acc ->
        match edge with
        | Next dest -> add_edge src dest acc
        | Branch (dest1, dest2) ->
            acc |> add_edge src dest1 |> add_edge src dest2)
      cfg.edges NodeMap.empty

  let transfer_function (cfg, aux) node in_values =
    Set.union (gen (cfg, aux) node) (Set.diff in_values (kill (cfg, aux) node))

  let join = match modality with May -> Set.union | Must -> Set.inter

  let initial_global_state (cfg, aux) =
    let bottom_state = compute_initial_state (cfg, aux) in
    NodeMap.map
      (fun _ -> { in_values = bottom_state; out_values = bottom_state })
      cfg.code_map

  let build_local_state in_values out_values =
    match direction with
    | Forward -> { in_values; out_values }
    | Backward -> { in_values = out_values; out_values = in_values }

  let get_in_values local_state =
    match direction with
    | Forward -> local_state.in_values
    | Backward -> local_state.out_values

  (** Implementation of the worklist algorithm for dataflow analysis. It
      initializes the worklist with the initial node of the CFG and iteratively
      processes nodes until a fixpoint is reached, meaning that no node's state
      changes anymore. The function returns the final global state of the
      analysis. It lazily updates the state of the successor nodes of a node
      whenever the state of that node changes, by adding the pending update to
      the worklist, in order to avoid reprocessing a successor node if it has
      been visited and the pending update does not change its state. *)
  let worklist_algorithm cfg =
    let edges = compute_edges cfg in
    let aux = compute_aux_info cfg in
    let initial_node = initial_node cfg in
    let initial_node_state = initial_node_state cfg in
    let initial_global_state = initial_global_state (cfg, aux) in
    let rec fixpoint_iteration worklist visited_nodes curr_state =
      match Queue.take_opt worklist with
      | None -> curr_state
      | Some (pending_update, curr_node) -> (
          let in_values = get_in_values (NodeMap.find curr_node curr_state) in
          let in_values' =
            if curr_node = initial_node then initial_node_state
            else join pending_update in_values
          in
          if
            NodeSet.mem curr_node visited_nodes
            && Set.equal in_values in_values'
          then fixpoint_iteration worklist visited_nodes curr_state
          else
            let out_values' =
              transfer_function (cfg, aux) curr_node in_values'
            in
            let analysis_state' =
              curr_state
              |> NodeMap.add curr_node
                   (build_local_state in_values' out_values')
            in
            let visited_nodes' = NodeSet.add curr_node visited_nodes in
            match NodeMap.find_opt curr_node edges with
            | None -> fixpoint_iteration worklist visited_nodes' analysis_state'
            | Some neighbourhood ->
                List.iter
                  (fun neighbour -> Queue.add (out_values', neighbour) worklist)
                  neighbourhood;
                fixpoint_iteration worklist visited_nodes' analysis_state')
    in
    let worklist = Queue.create () in
    Queue.add (Set.empty, initial_node) worklist;
    fixpoint_iteration worklist NodeSet.empty initial_global_state
end
